# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GMOrqruAIvXaLXi6JBh5ZT81n9EyrTAB
"""

import pandas as pd

# Sample DataFrame
data = {'A': [1, 2, 3, 4, 5],
        'B': [6, 7, 8, 9, 10],
        'C': [11, 12, 13, 14, 15]}
df = pd.DataFrame(data)

# Boolean logic to create a boolean mask
mask = (df['A'] > 2) & (df['B'] < 9)

# Access the DataFrame using the boolean mask
result = df[mask]

print(result)

import numpy as np

# Generate some random data
np.random.seed(0)
data = np.random.randn(100, 4)  # 100 samples, 4 features

# Calculate mean, median, standard deviation
mean_values = np.mean(data, axis=0)
median_values = np.median(data, axis=0)
std_deviation = np.std(data, axis=0)

print("Mean values:", mean_values)
print("Median values:", median_values)
print("Standard deviation:", std_deviation)

# Calculate correlation coefficient
correlation_matrix = np.corrcoef(data, rowvar=False)

print("Correlation coefficient matrix:")
print(correlation_matrix)